### ISSUE TITLE
Producer is coupled to consumer ?

### ISSUE THREAD

**Issue by gedw99** [ergo-services/examples#1]
https://github.com/ergo-services/examples/blob/master/cloud/producer/go.mod Is correct ?

Is this because the type is on the consumers side and you want the producer to send the consumer well known types ? 

Also this begs the question , do producers and consumers know about each other at compile time ?

**Comment by halturin** [comment]
>https://github.com/ergo-services/examples/blob/master/cloud/producer/go.mod Is correct ?

Yeah, this is correct, but it has an artifact :). The last line must be removed for sure (forgot to do that).


>Is this because the type is on the consumers side and you want the producer to send the consumer well known types ?

[producer imports consumer](https://github.com/ergo-services/examples/blob/master/cloud/producer/cmd/producer/producer.go#L10) to be known of the [consumer's message type](https://github.com/ergo-services/examples/blob/master/cloud/consumer/types.go#L5) 

>Also this begs the question , do producers and consumers know about each other at compile time ?

Ergo implements Erlang technologies, including [EPMD](https://www.erlang.org/doc/man/epmd.html). In Ergo this feature is embedded into the node, so you don't have to worry about that. It's like a local registrar of the running nodes keeping the node name and port number. Before making a TCP-connection, say to "abc@localhost", your node automatically resolves the port number requesting EMPD for the information where node "abc@localhsot" serves incoming connections. 

  - In this example, for regular network connection - the producer makes a connection to the consumer resolving the port number using [EPMD](https://github.com/ergo-services/ergo#epmd). 
  - for the cloud connection - once a node is connected to the cloud, it becomes a member of the cluster with a single virtual "namespace". All connections made to the *@"namespace" are routed through the cloud connection.

**Comment by gedw99** [comment]
> Yeah, this is correct, but it has an artifact :). The last line must be removed for sure (forgot to do that).

cool. thanks for letting me know.

**Comment by gedw99** [comment]
I am still new to this to even comment on how Types / protos work.  
I am used to using NATS, which you probably know.

If there a concept of a Registry with Ergo ? SO that a producer can ask the registry for the type at runtime ?

**Comment by halturin** [comment]
> I am used to using NATS, which you probably know.

Sure, I know it.

>SO that a producer can ask the registry for the type at runtime ?

Golang is a strongly typed language. So you just can't do that. In order to marshal/unmarshal messages from/to the specific type golang's runtime should be known the type of sending/receiving messages on the compile time. That's the reason for the existing `etf.RegisterType()` function.

**Comment by gedw99** [comment]
right. i need to learn more about how this works.  thanks for the explanation....
