### ISSUE TITLE
Error connecting to OTP 27

### ISSUE THREAD

**Issue by saleyn** [ergo-services/examples#4]
```
$ erl -name erl-demo@127.0.0.1 -setcookie 123
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Eshell V15.0 (press Ctrl+G to abort, type help(). for help)
(erl-demo@127.0.0.1)1> gen_server:call({example,'demo@127.0.0.1'}, hi).
(erl-demo@127.0.0.1)1> gen_server:call({example,'demo@127.0.0.1'}, hi).
=ERROR REPORT==== 16-Jul-2024::18:48:45.437207 ===
** 'erl-demo@127.0.0.1': Connection attempt to node 'demo@127.0.0.1' aborted since it cannot handle ["UNLINK_ID"].**
```

**Comment by halturin** [comment]
Please, use 'erlang' example from the v300 branch

**Comment by halturin** [comment]
Forgot to mention, you may also be interested to checkout there observer. It's web tool which embedded as an app into that node http://localhost:9911

**Comment by saleyn** [comment]
Getting the same error using v300 branch.  Tried two Erlang versions: 26.2.2 and 27.0 with same error as shown above.

**Comment by halturin** [comment]
Looks like you are still using the master branch of the ergo framework. Could you please share your code?

'erlang' example in the v300 branch uses ergo.services/proto/erland23 which supports 23..27 versions and it also points to the commit in v300 branch of Ergo Framework repo.

**Comment by halturin** [comment]
just double checked. works correctly
![image](https://github.com/user-attachments/assets/ebb26f30-8da3-4df7-ad2d-f10cf8b4f74a)

**Comment by saleyn** [comment]
I made a typo in branch switching.  I confirm that v300 works!  Sorry for noise. :(

**Comment by halturin** [comment]
np, happy to help. Don't miss the release :)  it's coming.
